### ISSUE TITLE
Animation playing issue.

### ISSUE THREAD

**Issue by ashutoshmaurya10** [warrenm/GLTFKit#2] opened 2018-01-30 12:54 UTC
Hi
I am working on playing , pausing my animations attached in the GLTF file but I am facing certain issue with Pivot and the axis for the nodes I am trying to apply the animations to.

Is there any sample which illustrates the playing and pausing of animations attached to respective nodes or any pointers for the same would be really helpful.

Thanks & Regards
Ashutosh

**Comment by warrenm** [comment] 2018-01-30 19:51
Hey @ashutoshmaurya10, sorry to hear about the difficulty. As written, this issue isn't actionable, but I'm interested in learning more. Pivots aren't a native concept in glTF, so exporters generally insert an extra "pivot node" relative to which rotations occur. Also, some exporters fail to correctly group channels and animations, which can result in unexpected animation. Which exporter are you using? Can you share the source model or glTF file?

**Comment by ashutoshmaurya10** [comment] 2018-01-31 05:21
Hi @warrenm , What would be the properties of the pivot inserted in terms of it being relative to its own coordinate system or world's. Also we are using blender to export the model in GLTF format.Attached is the model which we are trying to render and animate.
I am able to fetch the CAAnimationGroup object but when applied to the node for animation, the hierarchy of the model comes into play and the animation object doesn't transition to any state.
I am able to play and pause the scene to play the animations attached in an infinite loop but the control on animations and implementation nodes are still missing.

Thanks & Regards
Ashutosh
[GE_Anim_360_Rotate_gltf-glb.zip](https://github.com/warrenm/GLTFKit/files/1680511/GE_Anim_360_Rotate_gltf-glb.zip)

**Comment by warrenm** [comment] 2018-01-31 21:41
Every node's transform, regardless of whether it's a pivot node, expresses the relationship between the node's parent's coordinate system and the node's coordinate system.

My understanding is that the pivot would be an intermediate node between the node to be rotated and its parent node.  There is a translational relationship between the node and its pivot such that the node can rotate about the center of the pivot instead of the center of its own coordinate system. My presumption is therefore that the exporter would associate such rotations with the pivot rather than the child.

Can you describe the expected behavior of the attached model? It seems to rotate periodically about the vertical axis in both the SceneKit and Metal sample apps. I haven't tested it in other viewers, but it looks reasonable as far as I can tell.

As for an API for manipulating/pausing/playing scene animations, that's a great point. I struggled with how to make those animations available as separate objects, so for the time being, all animations are attached and running indefinitely by default. I recognize that that's not what many applications want, but I haven't found the time to design anything better yet. Apologies for the limitation.

**Comment by ashutoshmaurya10** [comment] 2018-02-01 08:08
Hi @warren ,
Yes while exporting the 3D model using Blender the animation objects are attached to either the node's pivot or the complete model's pivot. This binding once generated and exported cannot be modified using the provided properties either using Scenekit or Unity.
We need to add empty nodes and induce a parent relation with the node we want to apply the transformations to. I understand this point now that I need not manipulate/modify my Pivot in-order to apply transformations, I just need to add dependencies to the node I want to apply transformation to.
The model is attached with a single animation object which rotates the scene's root node by 360 degrees.
The method of having the animations files in a separate file is adopted in Unity but we really don't need to adopt this approach as we get the animation objects from the SceneSource object attached to the model using the animationKeys property for the selected/clicked node.
The problem for me here is not fetching the animation object but establishing the application of those animations at places where they were not applied in the 3D model.
I totally understand that this is a limitation for a lot of people as this is an entire new domain(controlling animations natively from exported 3D model files).
Thanks for the timely replies and your interest in our work. Let me know if you have any queries.

Regards
Ashutosh

**Comment by warrenm** [comment] 2018-05-14 13:12
@ashutoshmaurya10 Are there any action items remaining on this issue? I updated the animation API for SceneKit interop in 0134be94 (animations are now keyed by animation name instead of being glommed together in a single array). There's also an example of how to play/pause/stop individual animations in the SceneKit sample.

Let me know if I can do anything else to make this easier on you. I'll auto-close this issue in 7 days unless there's something left to do.

**Comment by warrenm** [comment] 2018-05-21 03:40
Closing due to inactivity.

**Closed by warrenm** 2018-05-21 03:40 UTC
