### ISSUE TITLE
Bone animations don't work in iOS12 and MacOS Mojave

### ISSUE THREAD

**Issue by AlexanderPetrovichev** [warrenm/GLTFKit#5] opened 2018-10-25 18:01 UTC
Just open any model with bones in SCN viewer. 
@warrenm take a look please.

**Comment by warrenm** [comment] 2018-10-25 18:56
I don't have the bandwidth to investigate regressions like this right now, but I'd gratefully accept a PR addressing the issue, if it can be solved within GLTFKit.

**Comment by AlexanderPetrovichev** [comment] 2018-10-25 19:04
I'm investigating it right now, but I don't have much experience in skeleton animations;) If you have some suggestions about how to localize this bug I check them.

**Comment by AlexanderPetrovichev** [comment] 2018-10-29 08:37
@warrenm Fix, maybe I'll create a PR later.

        float *weights = boneWeights.data.bytes;
        for (int i = 0; i < boneWeights.vectorCount; i += 1, weights += 4) {
            float k = weights[0] + weights[1] + weights[2] + weights[3];
            if (k != 1) {
                weights[0] = weights[0] / k;
                weights[1] = weights[1] / k;
                weights[2] = weights[2] / k;
                weights[3] = weights[3] / k;
            }
        }

**Comment by warrenm** [comment] 2018-10-29 17:44
Thanks for delving into this! I believe this is addressed by 2115d65; let me know if things are looking good.

This issue will be closed in seven days if no further activity takes place.

**Comment by warrenm** [comment] 2018-11-07 00:28
Closing due to inactivity.

**Closed as completed by warrenm** 2018-11-07 00:28 UTC

**Comment by sneha-belkhale** [comment] 2019-01-15 06:06
hey, @AlexanderPetrovichev , i'm running into the same issue where I have a model with bones, but the animation is not showing up on ios12. Were you able to confirm that this fix fixes the issue on ios12? I am testing with this model https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/RiggedFigure

**Comment by AlexanderPetrovichev** [comment] 2019-01-22 13:46
Yes, everything is working now in my project. @sneha-belkhale
